#!/usr/bin/fish

set -l LOCK_FILE ~/.wppvidlock
set -l IMG_PATH $argv[1]
set -l IMG_NAME (basename $IMG_PATH)
set -l IMG_CACHE ~/.cache/wpp/$IMG_NAME.JPG
ln -sf $IMG_PATH ~/.current_wpp
ln -sf $IMG_CACHE ~/.config/hypr/assets/LOCK.JPG

kill mpvpaper
switch (string split . $IMG_PATH | tail -n1)
    case mp4 MP4
        if not test -f $LOCK_FILE
            swww kill
            touch $LOCK_FILE
        end
        if not test -f $IMG_CACHE
            ffmpeg -i $IMG_PATH -vf "select=eq(n\,0)" -q:v 1 $IMG_CACHE
        end
        mpvpaper -o "--load-scripts=no --loop-playlist --hwdec=vaapi --panscan=1.0" '*' $IMG_PATH >/dev/null &
    case gif GIF
        if test -f $LOCK_FILE
            rm $LOCK_FILE
        end
        if not test -f $IMG_CACHE
            ffmpeg -i $IMG_PATH -vframes 1 $IMG_CACHE
        end
        swww query || swww-daemon &
        swww img --transition-type random $IMG_PATH >/dev/null
    case '*'
        if test -f $LOCK_FILE
            rm $LOCK_FILE
        end
        if not test -f $IMG_CACHE
            ffmpeg -i $IMG_PATH $IMG_CACHE
        end
        swww query || swww-daemon &
        swww img --transition-type random $IMG_PATH >/dev/null
end

wpg -ns "$IMG_CACHE"
matugen image "$IMG_CACHE"
wallust run "$IMG_CACHE"

cp ~/.cache/wallust/sequences ~/.cache/wal/sequences
sed -i 's/""/"~\/.config\/hypr\/assets\/LOCK.JPG"/g' ~/.cache/wal/colors.json

kitty @ set-colors -a -c ~/.config/kitty/colors.conf &
pywalfox update &
pkill -USR1 helix &
pkill -USR2 cava &
dunstctl reload &
~/.config/niri/scripts/swaybg_blur.sh "$IMG_NAME" &
gtk-update-icon-cache -ft ~/.local/share/icons/flattrcolor
gtk4-update-icon-cache -ft ~/.local/share/icons/flattrcolor
gsettings set org.gnome.desktop.interface gtk-theme Raleigh
gsettings set org.gnome.desktop.interface gtk-theme linea-nord-color
gsettings set org.gnome.desktop.interface icon-theme Adwaita
gsettings set org.gnome.desktop.interface icon-theme flattrcolor
