#!/usr/bin/fish

set -l PID (pidof wl-screenrec)

if [ $PID ]
    kill $PID
    pkill -f "$HOME/.config/niri/scripts/record_tray.py"
    notify-send "Screen Recording" "Screen Recording stopped"
else
    if [ $argv[1] = select ]
        wl-screenrec -f $HOME/Videos/Records/(date +'%Y-%m-%d %H-%M-%S').mp4 -g (slurp) &
    else
        wl-screenrec -f $HOME/Videos/Records/(date +'%Y-%m-%d %H-%M-%S').mp4 &
    end

    python -u "$HOME/.config/niri/scripts/record_tray.py" &
    notify-send "Screen Recording" "Screen Recording started"
end
