$background = rgb({{ background | rgb }})
$backgroundAlpha = {{ background | strip }}

$foreground = rgb({{ foreground | rgb }})
$foregroundAlpha = {{ foreground | strip }}

$accent = rgb({{ cursor | rgb }})
$accentAlpha = {{ cursor | strip }}
